### ISSUE TITLE
VS Code was unable to detect changes to HelloController.java

### ISSUE THREAD

**Issue by doddatpivotal** [sample-accelerators/tanzu-java-web-app#29]
Using the Tiltfile from the beta-3 branch, my VS Code could not detect changes I made to HelloController.java even though I had AutoBuild set to Enabled.  I found when I updated the Tiltfile to include the ant-style wildcard, then the reload occurred as I expected...

  ['pom.xml', './target/classes'],
  live_update = [
    sync('./target/classes**/**'**, '/workspace/BOOT-INF/classes')
  ],

**Comment by paulcwarren** [comment]
The sync rule is just a plain old operating system path and as far as I know none support the ant-style matchers like that.  I am half surprised that actually worked.  I suspect the underlying OS is being lenient with you there.  

Before it started working, did you see any errors in the tilt logs?

**Comment by amakhija** [comment]
Also, do you mind sharing a few more details here:

1. Could you share what your Tiltfile & workload.yaml look like?
2. What Kubernetes cluster are you running against? And what all do you have installed on that cluster?
3. What steps did you take before you saw this behavior? (E.g. deployed from CLI then started live update from the IDE)

**Comment by doddatpivotal** [comment]
Thank you for the feedback.  I will be do a fresh round of testing with the upcoming beta-4 release on 12/2.  I'll get responses quickly.

**Comment by cmoulliard** [comment]
> 1. Could you share what your Tiltfile & workload.yaml look like?

Workload file is available here: https://github.com/sample-accelerators/tanzu-java-web-app/blob/main/config/workload.yaml

> 2 What Kubernetes cluster are you running against? And what all do you have installed on that cluster?

   k8s: 1.21 and TAP 1.0

> 3. What steps did you take before you saw this behavior? (E.g. deployed from CLI then started live update from the IDE)
  
  I launched within VSCode : `Tanzu Live Update Up` (= tilt up)

**Comment by cmoulliard** [comment]
> Before it started working, did you see any errors in the tilt logs?

Error reported by buildpack during analyse phase was `[analyze] ERROR: failed to get previous image: missing OS for image "[ghcr.io/halkyonio/tanzu-java-web-app-tap-demo](http://ghcr.io/halkyonio/tanzu-java-web-app-tap-demo)"`

**Comment by doddatpivotal** [comment]
I am no longer facing this issue.  It must have been my local configuration and successive re-deploys of later TAP versions and cleaning up my environment, must have resolved the issue.
