### ISSUE TITLE
Question: Where can we find the "tanzu" app mentioned within Tilfile ?

### ISSUE THREAD

**Issue by cmoulliard** [sample-accelerators/tanzu-java-web-app#8]
### Question

Where can we find the `tanzu` app able to execute the following command `tanzu apps workload apply -f  ...` ?

https://github.com/sample-accelerators/tanzu-java-web-app/blob/main/Tiltfile#L2

**Comment by mingxiao** [comment]
the `tanzu` cli - https://github.com/vmware-tanzu/tanzu-framework/tree/main/cmd/cli#installation
the `apps` plugin https://github.com/vmware-tanzu/tanzu-cli-apps-plugins
